// Package smartcompose provides types for the Nylas Smart Compose API.
package smartcompose

// ComposeRequest contains the request data for smart compose.
type ComposeRequest struct {
	// Prompt is the text prompt that smart compose will use to generate a message suggestion.
	Prompt string `json:"prompt"`
}

// ComposeResponse contains the response from smart compose.
type ComposeResponse struct {
	// Suggestion is the message suggestion generated by smart compose.
	Suggestion string `json:"suggestion"`
}
